[alias]
	ad = add
	br = branch
	cl = clone
	cm = commit
	co = checkout
	cp = cherry-pick
	dd = !DELTA_FEATURES=+side-by-side git diff
	di = diff
	fe = fetch --all
	in = init
	lo = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
	ls = log --all --graph --decorate --oneline
	pl = pull
	pu = push
	ra = remote add
	rb = rebase
	re = remote --verbose
	ri = rebase -i
	sa = status
	sh = show
	sl = shortlog -sn
	sp = stash pop
	ss = status --short
	st = stash
	su = submodule update --recursive --remote --init
	sync = !git checkout master && git fetch --prune && git merge origin/master
	un = reset --soft HEAD~
