[colors.primary]
background = '#fff8f5'
foreground = '#1f1b18'

[colors.selection]
text = '#1f1b18'
background = '#8f6a49'

[colors.cursor]
text = '#fff8f5'
cursor = '#745233'

[colors.normal]
black   = '#161310'
red     = '#8c0b3b'
green   = '#327209'
yellow  = '#7f4b11'
blue    = '#e19043'
magenta = '#623e1d'
cyan    = '#745233'
white   = '#1a1a1a'

[colors.bright]
black   = '#2e2e2e'
red     = '#a52052'
green   = '#428c13'
yellow  = '#996021'
blue    = '#8b5e35'
magenta = '#ff7a3f'
cyan    = '#fff959'
white   = '#1a1a1a'
